### ISSUE TITLE
Add a rule for method calls in multiline blocks

### ISSUE THREAD

**Issue by theomelo** [rubocop/ruby-style-guide#865]
Hello fellow earthlings! 👋

Some folks coming from other languages background might feel inclined to add parenthesis surrounding method calls in multiline blocks. I personally don't think it's necessary since it doesn't disambiguate the order of execution in operations like the following:

```ruby
# this
    ary.map { |n|
      n * 4
      # Some
      # clever
      # things...
    }.select { |n|
      n == 4
      # More
      # clever
      # things...
    }.any? 

# as opposed to this
    ((
      ary.map { |n|
        n * 4
        # Some
        # clever
        # things...
      }
    ).select { |n|
        n == 4
      # More
      # clever
      # things...
    }).any? 
```

I'm curious to know if any of you think it would be something beneficial if we added a rule to Rubocop to ensure this rule, or if it's too specific. I would love to have some feedback before I can raise a PR! 🙌

**Comment by pirj** [comment]
To me those parenthesis look as redundant as in `((1 + 2) + 3)`. Would you like to send a PR adding a concise guideline to avoid using redundant parenthesis?

**Comment by theomelo** [comment]
> To me those parenthesis look as redundant as in `((1 + 2) + 3)`. Would you like to send a PR adding a concise guideline to avoid using redundant parenthesis?

Definitely! I just wanted some feedback on it to know if other folks think it would be beneficial to add a rule to Rubocop to ensure this is enforced or if it is too specific of a case.

**Comment by pirj** [comment]
Pretty sure there is no doubt among seasoned Ruby developers that those excessive parethesis are wrong. However, I believe we have a number of rules in the guide that nobody doubts, and still we have them.

I believe a short note with a couple of short examples mentioning redundant parenthesis will be beneficial. Please feel free to send a PR.

In cases when I see the code that looks weird, and reasoning that it is unreadable, uncommon and not canonical doesn't work - refering to the guide doesn't work either, unfortunately. Hope it will work for you.
