### ISSUE TITLE
Whitespace around certain operators

### ISSUE THREAD

**Issue by ShalokShalom** [rubocop/ruby-style-guide#880]
Why those three exceptions?

 [They read more readable to me](https://github.com/rubocop/ruby-style-guide#spaces-operators) with whitespace around.

What is the reasoning?

**Comment by pirj** [comment]
With `git blame` I could track it down to:

1. https://github.com/rubocop/ruby-style-guide/issues/553

Do you really prefer `foo &. bar`?

I must confess, it was a recent revelation to me that the dot should not necessarily be directly adjacent to the receiver and the method name. You want to avoid confusing newbies with your code, don't you?

2. https://github.com/rubocop/ruby-style-guide/issues/44

It's unfortunate that Ruby reserves `^` to bitwise XOR in the first place. I have no strong feelings about `e = M * c ** 2` vs `e = M * c**2`, but the vast majority of participants agree with the exception.

3. https://github.com/rubocop/ruby-style-guide/issues/659

The argument "visual distinction with division" sounds strong enough.


Do you object to some exception in particular, or all of them at once?
What is your suggestion for the style guide change?

**Comment by bbatsov** [comment]
We can probably add a bit of the rationale to the guidelines. I considered those self-explanatory, but I guess they are not.

**Comment by pirj** [comment]
There was even a ticket to handle that, but I gave up on the idea https://github.com/rubocop/ruby-style-guide/issues/749

**Comment by ShalokShalom** [comment]
Well, I like consistency.

The third example seems like the language messed up, and the style guide is here to fix this by breaking an already sane style guide, so its fixing a break with another break.

The second is kinda questionable, for the reason you provided.

The first one is a clear yes to the whitespace solution.

**Comment by pirj** [comment]
@ShalokShalom 

> The first one is a clear yes to the whitespace solution.

Please accept my apologies for reductio ad absurdum. If you prefer to use whitespace with the safe navigation operator, wouldn't it make sense for consistency also surround all method calls' dots to be surrounded by whitespace?
```ruby
cop = cop . cop_name if cop . respond_to?(:cop_name)
return if node . loc . operator . line == rhs . first_line
```

The style guide is based on the widespread practices.
If we'd adjust some guidelines, there would better be a proof that it is how it's used by Rubyists.

> A style guide that reflects real-world usage gets used, while a style guide that holds to an ideal that has been rejected by the people it is supposed to help risks not getting used at all - no matter how good it is.

Would you harvest https://github.com/eliotsykes/real-world-rails and https://github.com/jeromedalbert/real-world-ruby-apps for me to find a confirmation that at least some percentage of usages of `&.`, `**` and `/*r` have whitespace to them?

**Comment by ShalokShalom** [comment]
Oh sorry. I did mean this more as an informational request for me, rather than a suggestion to change your defaults.
