### ISSUE TITLE
Add guidance for safe navigation operator (`&.`)

### ISSUE THREAD

**Issue by andyw8** [rubocop/ruby-style-guide#889]
Reading https://thoughtbot.com/blog/ruby-safe-navigation reminded me that over-use of `&.` is common. I think it would be helpful to add a guideline such as:

> Avoid long chains of  `&.`. Replace with `.` if they introduce unnecessary conditional logic. Consider other approaches such as delegation.

This could also be added as a rule in RuboCop with a maximum number of chained calls (e.g. 2 or 3).

**Comment by bbatsov** [comment]
Yeah, I agree. We should definitely add some guidelines about `&.`.

**Comment by Gauravpurohit409** [comment]
Created PR for it please review it https://github.com/rubocop/ruby-style-guide/pull/912

**Comment by pirj** [comment]
Fixed in #912
