### ISSUE TITLE
Why not allowing multi-line ternary operator?

### ISSUE THREAD

**Issue by hacktivista** [rubocop/ruby-style-guide#894]
When using reasonably long explicative variables a ton of time you can't have a single line ternary operator, using ifs just makes the code bulkier, but does not improve readability.

```ruby
var = a ?
        b :
        c
```

tends to read better than

```ruby
var = if a
        b
      else
        c
      end
```

when you have only one liners.

I know I can change it on my own rubocop config, I just want to discuss the rule.

**Comment by marcandre** [comment]
If you replace `a`, `b` and `c` with longer expressions, you may notice that the information about what is going on is at the end of the lines with the ternary, while at it is at the beginning with the `if`. This makes it much more legible and recognizable.

In Ruby code, multi-line ternary operator is extremely unorthodox; I can't recall ever seeing one in open source code. This makes it even less readable as no reader expects it.

Note: I took the liberty to edit your text to turn on syntax highlighting, which makes the `if` standout even more.

**Comment by hacktivista** [comment]
A pattern I constantly want to use but never can is

```
var = a ?
        b : c
```

When the expression doesn't fit on one line. I use 80 columns line width.

**Comment by hacktivista** [comment]
A pattern I constantly want to use but don't use because of this recommendation is:

```ruby
a ?
  b : c
```

When it doesn't fit on one line... I use 80 characters as column width limit.
