### ISSUE TITLE
`using` in "Consistent Classes"

### ISSUE THREAD

**Issue by AlexWayfer** [rubocop/ruby-style-guide#905]
Ruby has refinements for a pretty long time.

I don't see `using` in [Consistent Classes](https://rubystyle.guide/#consistent-classes), as well as `refine` (but it's less priority).

**Comment by pirj** [comment]
Are refinements a feature sufficiently used to be mentioned?
At a glance, I could find [this](https://github.com/forem/forem/tree/main/app/refinements).
Can you find more in e.g. [`real-world-ruby-apps`](https://github.com/jeromedalbert/real-world-ruby-apps)?

**Comment by AlexWayfer** [comment]
> Are refinements a feature sufficiently used to be mentioned? At a glance, I could find [this](https://github.com/forem/forem/tree/main/app/refinements). Can you find more in e.g. [`real-world-ruby-apps`](https://github.com/jeromedalbert/real-world-ruby-apps)?

I don't know about "real world apps" repos, to be honest.

Some backstory, probably… 

I had a pretty difficult discussion a few years ago about `prepend`, which I liked that time. And my colleague has been referenced to this guide, that any `prepend` should be placed at the top of class definition, as well as `include`. There are confusions about `public` vs. `private`, if I place `include` (or `prepend` or `using`) under `private` — are public methods from joined module are private? Answer — no, but `prepend` is more complicated anyway.

So… I've seen a Twitter thread about ActiveSupport vs. refinements and remembered my own gem: https://twitter.com/soulcutter/status/1572578613471608834

And today I've been working on my (open-source) project after a long time, and this question about public-private popped up in my head again, and I've decided to check the Ruby Style Guide and found no answer to this.

During `using` works as well as `include` or `prepend`, I mean ignore placement under `private` or `protected`, I believe we should mention it among other keywords in the guide.

Don't you think so?

**Comment by pirj** [comment]
Please don't get me wrong, I'm all for AS to be reworked to be less intrusive, with refinements or else.

Putting `include` under method visibility modifiers is covered by the before mentioned guideline, even though there is no explanation in the guideline that including a module under `private` won't make methods private.

I'm only questioning the existence of real-life usage of refinements, considering this:

> A style guide that reflects real-world usage gets used

The style guide is not trying to be a definitive language guide, and is covering common mistakes and common good practices.

**Comment by AlexWayfer** [comment]
> The style guide is not trying to be a definitive language guide, and is covering common mistakes and common good practices.

OK: without a real-life apps (I can provide you one, but it's only one, I don't know fans of this approach, and I don't want to make "an ad" for it), how do you think: using `using` under `private` is a good practice? Or it worth to place it at the top of class definition?

**Comment by koic** [comment]
`using` is a special file scope that behaves differently depending on where it is used. I think it should not be covered in "Consistent Classes" section.
https://github.com/rubocop/rubocop/issues/10837#issuecomment-1196272400

**Comment by AlexWayfer** [comment]
> `using` is a special file scope that behaves differently depending on where it is used. I think it should not be covered in "Consistent Classes" section. [rubocop/rubocop#10837 (comment)](https://github.com/rubocop/rubocop/issues/10837#issuecomment-1196272400)

Interesting, didn't know this (or forgot). Thank you, then I guess we should close this issue…
