### ISSUE TITLE
Consider definining `#nil?` method a bad practice

### ISSUE THREAD

**Issue by FunkyloverOne** [rubocop/ruby-style-guide#909]
To begin with - if the `#nil?` method is defined to return `true` - the object is still considered truthy by Ruby.

Example:
```ruby
> puts 'blem' if object.client
# blem
#=> nil
> !!object.client
#=> true
> object.client.nil?
#=> true
> object.client.class.name
#=> "NullObjects::NullClient"
```

So in the example above there's a partially wrong implementation of the NullObject pattern, the NullObject should not pretend to be nil, it should do the opposite. :grin: 

Nothing should pretend to be nil really, therefore - it never makes sense to override the default `#nil?` method. :slightly_smiling_face:

**Comment by FunkyloverOne** [comment]
@pirj things become apparent when we have already thought them through, so I see the value in pointing it out so it is immediately apparent to everyone else :grin:

**Comment by pirj** [comment]
Off the top of my head, I can come up with some bad Ruby examples:
```ruby
# Do not override `hash`
class Evader
  def hash
    rand(1..1000)
  end
end
h = {}
key = Evader.new
h[key] = 1
h[key] # => nil
```
[Related](https://rubystyle.guide/#no-mutable-keys)

```ruby
# Is it a block or an argument?
[1,2].each.with_object {}
```

```ruby
# Guess why
[].each ()
ArgumentError: wrong number of arguments (given 1, expected 0)
```

We tend to leave out such bad examples from the guide, as they are ridiculous, even though it's easy to shot yourself in the leg and spend hours debugging.

There's a [Weird Ruby series](https://metaredux.com/tags/#weird-ruby), and I recall some weird things in WAT talks.

Are you confident all of this should get its way into the guide?

**Comment by FunkyloverOne** [comment]
Not so confident now. :grin: Alright then, closing this issue :slightly_smiling_face: 
TIL that `()` is `nil` in Ruby :ok_hand:
